### ISSUE TITLE
Version 2.1 release

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-firmware#51]
To do:
- [x] enable and check web update;
- [x] check `pynitrokey` update (development branch) - ~fails - https://github.com/Nitrokey/pynitrokey/issues/41~ - works!;

FIDO U2F and FIDO2 support tested on:
- [x] Windows 10, Mozilla Firefox 80
- [x]  Linux Fedora 31, Mozilla Firefox 82 (Nightly, 82.0a1 2020-08-31)
- [x] macOS 10.15.2 (Firefox 76, 80; Chrome 84-85; Safari 13.0.4)

Test sites used:
- https://u2f.bin.coffee/
- https://webauthn.bin.coffee/
- https://webauthn.io

Web Update (https://update.nitrokey.com/) paths tested:
- [x] 2.0 -> 2.1 (development firmware);
- [x] 2.1 -> 2.1 (development firmware, Linux);
- [x] 2.0 -> 2.1 (Windows);
- [x] 2.1 -> 2.1 (Windows, macOS).

Web Update tested on 2 production devices.

**Comment by beerisgood** [comment]
I can test help with testing Chromium-Edge under Windows10

**Comment by szszszsz** [comment]
@beerisgood That would be nice, thank you! It should be signed and released tomorrow for production tests (I will let you know), and after that announced wider.

**Comment by szszszsz** [comment]
@beerisgood It's live now on the https://update.nitrokey.com/ . Update seems to work on all platforms, as well as support for the FIDO U2F and FIDO2 features.

Edge is disabled, but can be forced using "Advanced Mode". While it should not be possible to break the device, there might be some UI/UX issues like even a browser freeze, but perhaps this improved - will be happy to hear that!  See below for details:
- https://github.com/Nitrokey/nitrokey-webupdate#supported-configurations

**Comment by beerisgood** [comment]
@szszszsz i test it with latest Chromium-Edge stable (version 85.0.564.44) and it work after i enable advanced mode!

Here my step by step:

- activate temporary advanced mode
-> version detection was sucessful:
![image](https://user-images.githubusercontent.com/9625159/92138235-69c9b100-ee0e-11ea-831b-2e70a8d9cc31.png)

- follow steps with touching the key if white light is blinking + cancel first Windows popup until the update process start, then wait/ do nothing until finished:
![image](https://user-images.githubusercontent.com/9625159/92138394-9a114f80-ee0e-11ea-9c05-632e1c8aaf4a.png)

- after browser restart, the version detection failed:
![image](https://user-images.githubusercontent.com/9625159/92138471-aeede300-ee0e-11ea-83ba-d960efe237b2.png)
-> maybe because i don't reload the site

- but after reloading site (i also remove and re-plugin the Nitrokey), it works:
![image](https://user-images.githubusercontent.com/9625159/92138541-c88f2a80-ee0e-11ea-8f5f-69bbf191571e.png)

**Comment by szszszsz** [comment]
Thank you for the report @beerisgood ! 
I am glad to hear it works with Edge - I will make retests for the next release and consider enabling back this one and other browsers on Windows.
I wonder what went wrong with the on-site firmware check (the red `SITE FIRMWARE OUT OF DATE` message). Some cache issues perhaps - will keep in mind to look into it.

**Comment by szszszsz** [comment]
No issues heard from the users since the release. Closing as done.
