### ISSUE TITLE
Changes in Version 2.1 & pynitrokey

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-fido2-firmware#52]
The 2.1. firmware version leads to some changes:
* `fido2 challenge-response` & `fido2 make-credential` require the pin to be provided, so added them as options or asking the user to provide it during execution.
* `fido2 reboot` fails with: `fido2.ctap.CtapError: CTAP error: 0x01 - INVALID_COMMAND`
* `fido2 reset` fails with: `fido2.ctap.CtapError: CTAP error: 0x30 - NOT_ALLOWED`

but apart from this, don't see other problems

**Comment by szszszsz** [comment]
Hi!

Sorry, the documentation for the changes is in progress, but you have found the biggest differences already I believe.

1. Reboot command AFAIR was removed from the production firmware, hence the `INVALID_COMMAND`.
2. FIDO2 reset does work only in the first 10 seconds of the device's power cycle - otherwise the NOT_ALLOWED error is shown. This error has to be handled properly in the client.

**Comment by jans23** [comment]
Why was the reboot command removed?

09.09.2020 19:05:31 Szczepan Zalega <notifications@github.com>:

> Hi!
> 
> Sorry, the documentation for the changes is in progress, but you have found the biggest differences already I believe.
> 
- * > Reboot command AFAIR was removed from the production firmware, hence the INVALID_COMMAND.
- * > FIDO2 reset does work only in the first 10 seconds of the device's power cycle - otherwise the NOT_ALLOWED error is shown. This error has to be handled properly in the client.

**Comment by szszszsz** [comment]
> Why was the reboot command removed?

I have just checked, and the reboot command works after user confirmation by a touch button. Sorry for confusion.

**Comment by daringer** [comment]
Good outcome I would say:
* `fido2 reboot` needs a confirmation by the touch button, will add this as a hint to the user on command execution
* `fido2 reset` also works fine the first 10secs after plugging the key in, will guide the user here, too

will be part of the upcoming 0.4.1 release

**Comment by daringer** [comment]
release done, issue(s) fixed, closing...
